security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        noauth:
            pattern: ^/(web|test)/
            security: false
        main:
            provider: app_user_provider
            pattern: ^/(app|_hb_post|_hb_get)/|^/public/build/auth.jsx$
            http_basic:
                realm: Secured Area
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false