security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User

    firewalls:
        noauth:
            pattern: ^/(web|test|_hb_public_get)/|^/_security/(register|validate-register|login)
            security: false
        main:
            provider: app_user_provider
            pattern: ^/(app|_hb_post|_hb_get|_contact)/|^/public/build/auth.jsx$|^/_security/(check-path|logout)
            json_login:
                check_path: /_security/check-path
                failure_handler : App\Manager\SecurityManager
            logout:
                path: /_security/logout
                target: /_security/login

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false