monolog:
    handlers:

        # Examples:
        syslog:
            type:                stream
            path:                %kernel.root_dir%/var/logs/symfony.log
            level:               ERROR
            bubble:              false
            formatter:           my_formatter
        main:
            type:                fingers_crossed
            action_level:        WARNING
            # By default, buffer_size is unlimited (0), which could
            # generate huge logs.
            buffer_size:         0
            handler:             custom
        console:
            type:                console
            verbosity_levels:
                VERBOSITY_NORMAL:       WARNING
                VERBOSITY_VERBOSE:      NOTICE
                VERBOSITY_VERY_VERBOSE: INFO
                VERBOSITY_DEBUG:        DEBUG
        custom:
            type:                service
            id:                  my_handler

        # Default options and values for some "my_custom_handler"
        # Note: many of these options are specific to the "type".
        # For example, the 'service' type doesn't use any options
        # except id and channels
        my_custom_handler:
            type:                 ~ # Required
            id:                   ~
            priority:             0
            level:                DEBUG
            bubble:               true
            path:                 '%kernel.logs_dir%/%kernel.environment%.log'
            ident:                false
            facility:             user
            max_files:            0
            action_level:         WARNING
            activation_strategy:  ~
            stop_buffering:       true
            buffer_size:          0
            handler:              ~
            members:              []
            channels:
                type:     ~
                elements: ~
            from_email:           ~
            to_email:             ~
            subject:              ~
            mailer:               ~
            email_prototype:
                id:                   ~ # Required (when the email_prototype is used)
                method:               ~
            formatter:            ~
    # Set to false to use seconds (instead of microseconds) in
    # the logs (gives a small performance boost).
    use_microseconds:             true