imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    assets:
       font-awesome-css:
          inputs: '@AppBundle/Resources/third-party/font-awesome/css/font-awesome.css'
          output: '/Resources/third-party/font-awesome/css/font-awesome.css'
       font-awesome-eot: 
          inputs: '@AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.eot'
          output: 'Resources/third-party/font-awesome/fonts/fontawesome-webfont.eot'
       font-awesome-otf: 
          inputs: '@AppBundle/Resources/third-party/font-awesome/fonts/FontAwesome.otf'
          output: '/Resources/third-party/font-awesome/fonts/fontawesome-webfont.otf'    
       font-awesome-svg: 
          inputs: '@AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.svg'
          output: '/Resources/third-party/font-awesome/fonts/fontawesome-webfont.svg'
       font-awesome-ttf: 
          inputs: '@AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.ttf'
          output: '/Resources/third-party/font-awesome/fonts/fontawesome-webfont.ttf' 
       font-awesome-woff: 
          inputs: '@AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.woff'
          output: '/Resources/third-party/font-awesome/fonts/fontawesome-webfont.woff' 
       font-awesome-woff2: 
          inputs: '@AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.woff2'
          output: '/Resources/third-party/font-awesome/fonts/fontawesome-webfont.woff2'  
       glyphicons-halflings-regular-ttf:
          inputs: '@AppBundle/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.ttf'
          output: '/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.ttf'
       glyphicons-halflings-regular-woff:
          inputs: '@AppBundle/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.woff'
          output: '/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.woff'   
       glyphicons-halflings-regular-woff2:
          inputs: '@AppBundle/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.woff2'
          output: '/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.woff2'
       icheck-square-blue:
          inputs: '@AppBundle/resources/third-party/iCheck/css/square/blue.png'
          output: '/resources/third-party/iCheck/css/square/blue.png'    
       icheck-square-blue2:
          inputs: '@AppBundle/resources/third-party/iCheck/css/square/blue@2x.png'
          output: '/resources/third-party/iCheck/css/square/blue@2x.png'              
       ionicons-ttf:
          inputs: '@AppBundle/Resources/third-party/ionicons/fonts/ionicons.ttf'
          output: '/Resources/third-party/ionicons/fonts/ionicons.ttf'  
       ionicons-woff:
          inputs: '@AppBundle/Resources/third-party/ionicons/fonts/ionicons.woff'
          output: '/Resources/third-party/ionicons/fonts/ionicons.woff'                                                                                                           
       tinymce-css: 
          inputs: '@AppBundle/Resources/third-party/tinymce/tests/manual/css/development.css'
          output: '/Resources/third-party/tinymce/css/development.css'   
       tinymce-skin-css: 
          inputs: '@AppBundle/Resources/third-party/tinymce/js/tinymce/skins/lightgray/skin.min.css'
          output: '/js/skins/lightgray/skin.min.css'
       tinymce-ttf: 
          inputs: '@AppBundle/Resources/third-party/tinymce/js/tinymce/skins/lightgray/fonts/tinymce.ttf'
          output: '/js/skins/lightgray/fonts/tinymce.ttf' 
       tinymce-woff: 
          inputs: '@AppBundle/Resources/third-party/tinymce/js/tinymce/skins/lightgray/fonts/tinymce.woff'
          output: '/js/skins/lightgray/fonts/tinymce.woff'    
       tinymce-autolink: 
          inputs: '@AppBundle/Resources/third-party/tinymce/js/tinymce/plugins/autolink/plugin.js'
          output: '/js/plugins/autolink/plugin.js'               
                  
    filters:
        cssrewrite: ~ 
        jsqueeze: ~   

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
