imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/AppBundle/Resources/views": AppBundle

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    assets:
       jquery-ui-icons:
          inputs:
          - '../src/AppBundle/Resources/third-party/jQueryUI/images/ui-icons_444444_256x240.png'
          - '../src/AppBundle/Resources/third-party/jQueryUI/images/ui-icons_555555_256x240.png'
          - '../src/AppBundle/Resources/third-party/jQueryUI/images/ui-icons_777620_256x240.png'
          - '../src/AppBundle/Resources/third-party/jQueryUI/images/ui-icons_777777_256x240.png'
          output: 'css/images/ui-icons_444444_256x240.png'
       app-css:
          inputs:
          - '../src/AppBundle/Resources/third-party/bootstrap/css/bootstrap.min.css'
          - '../src/AppBundle/Resources/third-party/bootstrap-table/css/bootstrap-table.min.css'
          - '../src/AppBundle/Resources/third-party/jQueryUI/jquery-ui.theme.min.css'
          - '../src/AppBundle/Resources/third-party/jQueryUI/jquery-ui.css'
          - '../src/AppBundle/Resources/third-party/AdminLTE/css/AdminLTE.min.css'
          - '../src/AppBundle/Resources/third-party/AdminLTE/css/skins/_all-skins.min.css'
          - '../src/AppBundle/Resources/third-party/font-awesome/css/font-awesome.css'
          - '../src/AppBundle/Resources/third-party/iCheck/css/square/blue.css'
          - '../src/AppBundle/Resources/hbase/css/hbase.css'
          output: 'css/app-css.css'
       font-awesome-eot:
          inputs: '../src/AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.eot'
          output: 'fonts/fontawesome-webfont.eot'
       font-awesome-otf:
          inputs: '../src/AppBundle/Resources/third-party/font-awesome/fonts/FontAwesome.otf'
          output: 'fonts/fontawesome-webfont.otf'
       font-awesome-svg:
          inputs: '../src/AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.svg'
          output: 'fonts/fontawesome-webfont.svg'
       font-awesome-ttf:
          inputs: '../src/AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.ttf'
          output: 'fonts/fontawesome-webfont.ttf'
       font-awesome-woff:
          inputs: '../src/AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.woff'
          output: 'fonts/fontawesome-webfont.woff'
       font-awesome-woff2:
          inputs: '../src/AppBundle/Resources/third-party/font-awesome/fonts/fontawesome-webfont.woff2'
          output: 'fonts/fontawesome-webfont.woff2'
       glyphicons-halflings-regular-ttf:
          inputs: '../src/AppBundle/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.ttf'
          output: 'fonts/glyphicons-halflings-regular.ttf'
       glyphicons-halflings-regular-woff:
          inputs: '../src/AppBundle/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.woff'
          output: 'fonts/glyphicons-halflings-regular.woff'
       glyphicons-halflings-regular-woff2:
          inputs: '../src/AppBundle/Resources/third-party/bootstrap/fonts/glyphicons-halflings-regular.woff2'
          output: 'fonts/glyphicons-halflings-regular.woff2'
       icheck-square-blue:
          inputs: '../src/AppBundle/Resources/third-party/iCheck/css/square/blue.png'
          output: 'css/square/blue.png'
       icheck-square-blue2:
          inputs: '../src/AppBundle/Resources/third-party/iCheck/css/square/blue@2x.png'
          output: 'css/square/blue@2x.png'
       ionicons-ttf:
          inputs: '../src/AppBundle/Resources/third-party/ionicons/fonts/ionicons.ttf'
          output: 'fonts/ionicons.ttf'
       ionicons-woff:
          inputs: '../src/AppBundle/Resources/third-party/ionicons/fonts/ionicons.woff'
          output: 'fonts/ionicons.woff'
       tinymce-css:
          inputs: '../src/AppBundle/Resources/third-party/tinymce/tests/manual/css/development.css'
          output: 'css/development.css'
       tinymce-skin-css:
          inputs: '../src/AppBundle/Resources/third-party/tinymce/js/tinymce/skins/lightgray/skin.min.css'
          output: 'js/skins/lightgray/skin.min.css'
       tinymce-ttf:
          inputs: '../src/AppBundle/Resources/third-party/tinymce/js/tinymce/skins/lightgray/fonts/tinymce.ttf'
          output: 'js/skins/lightgray/fonts/tinymce.ttf'
       tinymce-woff:
          inputs: '../src/AppBundle/Resources/third-party/tinymce/js/tinymce/skins/lightgray/fonts/tinymce.woff'
          output: 'js/skins/lightgray/fonts/tinymce.woff'
       tinymce-autolink:
          inputs: '../src/AppBundle/Resources/third-party/tinymce/js/tinymce/plugins/autolink/plugin.js'
          output: 'js/plugins/autolink/plugin.js'

    filters:
        cssrewrite: ~
        jsqueeze: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                CONCAT_WS: AppBundle\DQL\ConcatWs
            numeric_functions:
                FLOOR: AppBundle\DQL\Floor
                IF: AppBundle\DQL\IfElse
                IFNULL: AppBundle\DQL\IfNull
            datetime_functions:
                DATE_FORMAT: AppBundle\DQL\DateFormat

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
