entity:
    resource: "@EntityBundle/Controller/"
    type:     annotation
    prefix:   /

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /article

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: ~
