entity:
    resource: "@EntityBundle/Controller/"
    type:     annotation
    prefix:   /

article:
    resource: "@ArticleBundle/Controller/"
    type:     annotation
    prefix:   /article

platform:
    resource: "@PlatformBundle/Controller/"
    type:     annotation
    prefix:   /platform

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
