app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: ~
    
homepage:     
    path:   /
    defaults:  { _controller: 'AppBundle:Default:index' }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
    
    