# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 15
        

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main_provider: 
           entity:
               class: AppBundle:User
               property: username
               
               
    access_control:    
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY
          }        
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY
          }   

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
              

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path: homepage
                
                
            logout:
                path: logout
                target: login    
                
            provider: main_provider
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
