web_profiler:
    toolbar:              '%kernel.debug%'
    intercept_redirects:  true
    #excluded_ajax_paths:  '^/((index|app(_[\w]+)?)\.php/)?_wdt'

framework:
    profiler: { only_exceptions: false }